# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

case_a <- function(df, score, suiClass, Min, Max, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma) {
    .Call('ALUES_case_a', PACKAGE = 'ALUES', df, score, suiClass, Min, Max, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma)
}

case_b <- function(df, score, suiClass, Min, Max, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma) {
    .Call('ALUES_case_b', PACKAGE = 'ALUES', df, score, suiClass, Min, Max, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma)
}

case_c <- function(df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, d, e, f, l1, l2, l3, l4, l5, sigma) {
    .Call('ALUES_case_c', PACKAGE = 'ALUES', df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, d, e, f, l1, l2, l3, l4, l5, sigma)
}

case_d <- function(df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, d, l1, l2, l3, l4, l5, sigma) {
    .Call('ALUES_case_d', PACKAGE = 'ALUES', df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, d, l1, l2, l3, l4, l5, sigma)
}

case_e <- function(df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma) {
    .Call('ALUES_case_e', PACKAGE = 'ALUES', df, score, suiClass, Min, Max, Mid, mfNum, bias, wt, j, a, b, c, l1, l2, l3, l4, l5, sigma)
}

